"""Translate the actual epdiy GC16 table, preserving its packed old-gray order."""
import ast
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'datasheet/src/ES120MC1-EpdiyV7/lib/epdiy2/src/waveforms/epdiy_ED047TC1.h'
RTL = ROOT / 'eink/c/p/Eink_controller_V1.0.srcs/sources_1/new'
OUT = ROOT / 'eink/build/hdmi_native_gc16_20260920'


def load_table():
    source = SOURCE.read_text()
    match = re.search(r'epd_wp_epdiy_ED047TC1_2_0_data[^=]*=\s*(\{.*?\});', source, re.S)
    if not match:
        raise ValueError('GC16 table missing')
    table = ast.literal_eval(match[1].replace('{', '[').replace('}', ']'))
    assert len(table) == 30
    assert all(len(phase) == 16 and all(len(row) == 4 for row in phase) for phase in table)
    return table


if __name__ == '__main__':
    table = load_table()
    codes = [0] * 8192
    for phase in range(30):
        for target in range(16):
            for old in range(16):
                packed = table[phase][target][old // 4]
                codes[phase * 256 + target * 16 + old] = (packed >> (6 - 2 * (old % 4))) & 3
    assert 3 not in codes, 'Reserved drive code in reference waveform'
    lines = [
        '// Generated by tests/generate_es120_gc16.py; do not edit the table.',
        '// Source: epdiy_ED047TC1 MODE_GC16 (2), temperature interval 20..30 C.',
        '// Address = {zero-based phase, target gray, previous gray}.',
        'module gc16_lut_es120mc1(input wire clk, input wire [4:0] phase,',
        '    input wire [7:0] transition, output reg [1:0] drive);',
        '    (* rom_style = "block" *) reg [1:0] lut [0:8191];',
        '    initial begin',
    ]
    lines += [f"        lut[13'd{i}] = 2'd{v};" for i, v in enumerate(codes)]
    lines += ['    end', '    always @(posedge clk) drive <= lut[{phase, transition}];', 'endmodule', '']
    (RTL / 'gc16_lut_es120mc1.v').write_text('\n'.join(lines), encoding='ascii')
    OUT.mkdir(exist_ok=True)
    (OUT / 'gc16_reference.mem').write_text('\n'.join(f'{v:x}' for v in codes) + '\n')
    manifest = {'source': str(SOURCE), 'source_sha256': hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
                'phases': 30, 'transitions_per_phase': 256, 'codes_sha256': hashlib.sha256(bytes(codes)).hexdigest()}
    (OUT / 'gc16_reference.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(json.dumps(manifest, indent=2))
